preset:
  - psr1
  - psr2
  - symfony

enabled:
  - short_array_syntax
  - heredoc_to_nowdoc
  - linebreak_after_opening_tag
  - no_useless_return
  - not_operator_with_successor_space
  - ordered_class_elements
  - alpha_ordered_imports
  - phpdoc_add_missing_param_annotation
  - phpdoc_order
  - phpdoc_types_order

finder:
  name: "*.php"
  exclude:
    - vendor